integrations:
  git:
    pre_commit_hooks: true
    branch_detection: true
    commit_message_validation: true
    
  ci_cd:
    github_actions: true
    gitlab_ci: true
    jenkins: true
    azure_devops: true
    
  monitoring:
    prometheus_metrics: true
    grafana_dashboards: true
    alertmanager_rules: true
    
  development:
    vscode_extension: true
    ide_integration: true
    real_time_feedback: true
